#!/bin/sh

if getconf GNU_GLIBC_VERSION > /dev/null 2>&1 ; then
    exec $0-glibc.sh $@
elif [ "$(uname)" = "FreeBSD" ] ; then
    exec $0-freebsd.sh $@
else
    echo "Unsupported OS, patches welcome" >&2
    exit 1
fi
